### ISSUE TITLE
ninja dependency?

### ISSUE THREAD

**Issue by fossfreedom** [asermax/lastfm_extension#16]
@asermax 

I'm trying to produce a new deb package from your newly refactored code...

<pre>

Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/lastfm_extension/lastfm_extension.py", line 37, in <module>
    from ninja_ide.gui.menus.lib.aboutdialog import keys_desc
ImportError: No module named ninja_ide.gui.menus.lib.aboutdialog

</pre>

I dont recognise that python package - any ideas?

**Comment by asermax** [comment]
It's probably an auto import made by my IDE by mistake, it's safe to remove it.

**Comment by asermax** [comment]
I don't find this import anywhere, I might have removed it in a previous commit, but I'm not sure. You're still having this problem? If you do, may you help me find the import?

**Comment by fossfreedom** [comment]
its vanished - well I'm flummoxed - as you can see it definitely was in lastfmextension.py - now its gone.

I'll close this - BTW I've had to shift a few files around 

/usr/lib... should have these files:

<pre>
genres.txt                      LastFMExtensionGui.py   lastfm_extension.plugin  LastFMExtensionUtils.py  README.md
LastFMExtensionGenreGuesser.py  LastFMExtensionKeys.py  lastfm_extension.py      pylast.py
</pre>

All other files need to be in /usr/share...

The exception seems to be LastFMExtensionKeys.py that needs to be in both `share` and `lib` - matcher.py seems to need LastFMExtensionKeys.py in the share folder as itself (matcher.py doesnt seem to run from lib), whereas the whole plugin needs LastFMExtensionKeys.py in the lib folder
- http://ubuntuone.com/5VNNEvP08KXtRDJHeqP7ZT

Also - what test(s) are you using to see that the two sync plugins are copying stuff back and from LastFM?

**Comment by asermax** [comment]
Hmm the matcher doesn't run from `lib` because it's run on a subprocess to prevent Rhythmbox from crashing (for some reason I can't run the fingerprinting library from within Rhythmbox python enviroment). I will implement a workaround to add the `LastFMExtensionKeys` directory to the `PYTHONPATH` for the subprocess, I'm guessing that way it will work as it should. 

For testing I just do manual tests with some songs I know what results should give for the syncing xD (e.g. remove and readd a song to check if the playcount gets updated; reset a loved songs rating to check if it's synced to 5 stars again after playing it). Oh, and the sync is just from lastfm to Rhythmbox; there's no API for doing it the other way around.

**Comment by asermax** [comment]
Oops, forgot to reference the issue from the commit. 0145fa8 introduces the workaround I mentioned. If you have some time, test it out!

**Comment by fossfreedom** [comment]
looks good :)

BTW - lastfm-extension is one of the more popular downloads from my PPA - close to 10,000 downloads the last time I looked.  So - well done, I'm sure those users will be excited with the refresh.

**Comment by asermax** [comment]
Wut, 10000? That's a lot more than what I imagined xD I mean, some people contacted me for some issues on the installation process or with some recommendations, but I never thought there would be so many users.
Anyway, now that I finished with the refactoring, I will start implementing the enhancements that I left hanging on the issues list :F
