### ISSUE TITLE
new settings.conf file prevents global installation

### ISSUE THREAD

**Issue by fossfreedom** [asermax/lastfm_extension#17]
The move to a settings.conf file means that when it is installed in the global location ... /usr/share/rhythmbox/lastfm_extension, a user no longer has read-write access to that file

This results in the following error when they attempt to untick one of the extensions in the preferences dialog:

<pre>
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/lastfm_extension/lastfm_extension.py", line 217, in toggled_callback
    self.enabled = checkbox.get_active()
  File "/usr/lib/rhythmbox/plugins/lastfm_extension/lastfm_extension.py", line 113, in enabled
    self.settings.set(Keys.ENABLED, enable)
  File "/usr/lib/rhythmbox/plugins/lastfm_extension/LastFMExtensionUtils.py", line 151, in call_with_section
    return getattr(self._settings, attr)(self._section, *args, **kwargs)
  File "/usr/lib/rhythmbox/plugins/lastfm_extension/LastFMExtensionUtils.py", line 140, in set
    self.save()
  File "/usr/lib/rhythmbox/plugins/lastfm_extension/LastFMExtensionUtils.py", line 113, in save
    with open(self._config_file, 'w') as conf_file:
IOError: [Errno 13] Permission denied: '/usr/share/rhythmbox/plugins/lastfm_extension/settings.conf'

</pre>

Now I suppose I can get around this by opening up the permissions to 777 for this file - from a deb packaging POV - definitely frowned upon.

Why the move away from dconf that was in the previous version?

**Comment by asermax** [comment]
Because dconf isn't dynamical enough for what intend to do. I want to keep extending the last fm functionality by adding more and more drop in extensions and allow other people to easily extend the plugin too.
More than anything else, the change was for personal preference, I find it easier to work with a conf file.
In a global installation scenario, the settings file should be instanced in a per user basis. Probably the best way to achieve this is to change the settings file to the user home as a hidden file, or find a way to always use the user .local path.
I'll look at it later.

**Comment by asermax** [comment]
I made some changes to always create the file on the user's directory. Let me know if this change solves the problem!

**Comment by fossfreedom** [comment]
ok - that looks good - I was a little surprised to see this in ~/.local/share/rhythmbox/plugins/lastfmextension

I though this sort of stuff (http://www.jetmore.org/john/misc/rb/rb297-python-bindings/RB.find_user_data_file.html) should be at the same level as rhythmdb.xml ? - anyway its probably more obvious your way.

**Comment by asermax** [comment]
I think it should be in a plugin specific directory, but I could use `find_user_data_file` instead of a hardcoded path. I'll change that and close this one.
