### ISSUE TITLE
Fails to love/ban songs with non-ascii charaters on title or artist name

### ISSUE THREAD

**Issue by fossfreedom** [asermax/lastfm_extension#2]
dad@dad-VirtualBox:~/Downloads/rhythmbox-plugins$ Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/lastfm_extension/lastfm_extension.py", line 191, in love_track
    ( track.get_title(), track.get_artist() )
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

I got the above error when playing standard non lastfm music and I hit the love/ban button which were active.  I wasnt sure if the buttons were supposed to be active on non-lastfm music - is this another issue?

Anyway, this got me thinking - you can activate the lastfmextension without the lastfm plugin - I presume these two extensions should be simultaneously activated?

I think there is a missing dependency - perhaps add "Depends=lastfm" to the .plugin file to ensure that when activating this plugin, the lastfm plugin is also activated - likewise, if deactivating lastfm, then lastfmextension will also be deactivated.

Note - "lastfm" is a guess on my part - not sure what the module name is in the lastfm plugin is since  I dont see an obvious /usr/lib/rhythmbox/plugins file for this plugin.

**Comment by asermax** [comment]
This plugin is independent from the lastfm plugin that comes with rhythmbox; I preferred to use a third-party python API that was easier to use (the API is included in the plugin files). That's why you have to login separately.

The error you encountered is something that i hadn't tested while developing the plugin, that's trying to love/ban songs with non-ascii titles (e.g. some asian character). I asume your error came up under those circunstances, if I'm wrong please let me know.
Anyway, I gonna push a little change that seems to fix the problem (if it's what i think). I tested it in some songs with japanse chars and seems to work fine. If you have a chance, please test it out.

**Comment by fossfreedom** [comment]
ok cheers - will test this this evening.  It was a bit of celion dion (no comment please on the choice of music :D  ) - she has an accent character in her name.

Just to confirm - the love/ban buttons are supposed to  be activated for non-lastfm music e.g. just playing music imported from my CD player?

I understand about the third party API aspect - I was querying whether this extension should be "tied" with the default lastfm plugin from a user point of view - 

consider this use case: the user is deactivating various plugins and he deactivates lastfm - maybe the lastfm-extension plugin should also be automatically deactivated.  By putting the depends value in the .plugin file this would be enforced.

Likewise - use case - the user has activated lastfm-extension ... but did not remember to activate lastfm extension as well - the depends value will automatically activate the lastfm extension for him.

**Comment by asermax** [comment]
Yes, the love and ban buttons should be activated and work regardless the music source.

As for the dependency, I guess it makes sense to tie the lastfm_extension to the lastfm plugin, since it's supposed to be extension to that plugin capabilities. But since they are functionally independent, I don't really know if it's worth enforcing such rule. For now, I'll let it be as it is, but I will take it into account. Thanks for the idea :D

PS: I like celine dion too, lol d:

**Comment by fossfreedom** [comment]
yep - that fix works for the love button.  Just need the similar fix for the ban track as well (line 209) of the same module.  Thanks.

**Comment by asermax** [comment]
I didn't even realized, I'll fix it right away.

I'll mark this issue as closed, thanks for the feedback!
