### ISSUE TITLE
Fingerprint does not work

### ISSUE THREAD

**Issue by austris-argalis** [asermax/lastfm_extension#21]
Hello there!
I have installed lastfm_extension but fingerprint feature is not working. When i launch fingerprint in console shows up this error:

```
Traceback (most recent call last):
    File "/home/austris/.local/share/rhythmbox/plugins/lastfm_extension/matcher.py", line 35,    in <module>
      'track':title })
    File "/usr/local/lib/python2.7/dist-packages/lastfp/__init__.py", line 262, in match_file
      with audioread.audio_open(path) as f:
    File "/usr/local/lib/python2.7/dist-packages/audioread/__init__.py", line 96, in audio_open
        raise NoBackendError()
audioread.NoBackendError
```

i tried upgrading pylastfp package but it is already newest, and also some times deleted extension from .local/share/rhythmbox .. un launched install.sh, but it also doesn`t help.

Thanks, hope you can help.

**Comment by asermax** [comment]
```
File "/usr/local/lib/python2.7/dist-packages/audioread/__init__.py", line 96, in audio_open
        raise NoBackendError()
```

This last line gives a hint that the problem lies within `audioread`, and as the exeption mentions, it probably haves to do with the library not being able to find a suitable backend.
[Here](https://github.com/sampsyo/audioread) you can find the list of supported backends for the library. Make sure you have at least one of those installed on your system and try using the fingerpirnting feature again.
If you have any other problem, feel free to ask over here, but if it's related to this same exception it probably gonna be more productive to ask on the `audioread` issue tracker (since I don't know much more about the library than what I already said here xD).

**Comment by austris-argalis** [comment]
You was right, all I had to do was install ffmpeg package, and everything went fine.
Thanks alot!
