### ISSUE TITLE
Not working with rhythmbox 3.0.1

### ISSUE THREAD

**Issue by XenGi** [asermax/lastfm_extension#23]
The plugin can't be loaded with rhythmbox v3.0.1. Rhythmbox gives the folloing output when I try to activate the plugin.

```
$ rhythmbox

(rhythmbox:6398): Gtk-WARNING **: Theme parsing error: gtk.css:72:18: Not using units is deprecated. Assuming 'px'.

(rhythmbox:6398): Gtk-WARNING **: Theme parsing error: gtk.css:72:20: Not using units is deprecated. Assuming 'px'.

(rhythmbox:6398): Gtk-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files

(rhythmbox:6398): Rhythmbox-WARNING **: Unable to grab media player keys: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SettingsDaemon was not provided by any .service files

(rhythmbox:6398): libpeas-WARNING **: Could not find loader 'python' for plugin 'lastfm_extension'
```

**Comment by asermax** [comment]
Just a heads up: I'm not mantaining this plugin anymore, given that I don't use rhythmbox anymore.
Said that, the important line on your dump is probably

```
(rhythmbox:6398): libpeas-WARNING **: Could not find loader 'python' for plugin 'lastfm_extension'
```

Since RB 3.0 (I think) they started using python3 instead of python2 for plugins, and changed the plugin `Loader` directive to reflect that.
You can try modifying the `lastfm_extension.plugin` file, changing the second line `Loader=python` for `Loader=python3`. I'm not really sure if it's going to work (i don't remeber doing any python3 refactoring), but you can try.

Cheers.

**Comment by XenGi** [comment]
I tried porting this to python3 but I don't have time for this now. Which last.fm capable player do you use now? I tried clementine but wasn't that much satisfied.

**Comment by asermax** [comment]
I tried a couple of players but ended up with Clementine. It doesn't have all the features I want, but at least doesn't break everything on each new release d:
