### ISSUE TITLE
finger print invoking query

### ISSUE THREAD

**Issue by fossfreedom** [asermax/lastfm_extension#5]
Asermax,
  wonderful idea for the fingerprinting stuff :)

Will you be invoking the fingerprinting  stuff as per banshee via a rightclick option?

This screenshot will show what I'm talking about:

http://askubuntu.com/questions/171989/get-track-information-from-internet-in-rhythmbox

**Comment by asermax** [comment]
Yes, the idea is using the contextual menu to activate the fingerprinting proccess. 
There is one difference tho: if I remember correctly, Banshee automatically updates your song metadata after asking for the fingerprint. My idea is to popup a dialog with the different options LastFM proposes for the fingerprinted track.

You can test out this feature (I would say it's still in 'beta', but it's functional) downloading the fingerprint branch on the repo: [Fingerprint Branch](https://github.com/asermax/lastfm_extension/zipball/fingerprint).

For this feature to work, you will also need to install [pylastfp](http://pypi.python.org/pypi/pylastfp/0.1), since the plugin uses that module to get the fingerprinting done. I decided not to ship it with the plugin itself, since pylastfp includes native compiled libraries, which could cause conflicts.

**Comment by fossfreedom** [comment]
ok - will have a look.  Hmm - I need to think through how to .deb the pylastfp install though...

**Comment by asermax** [comment]
I'm not very familiar with how .deb packages are made and how they work, but maybe this can help http://pypi.python.org/pypi/stdeb. 
Anyway, please test out the fingerprinting feature and let me know of any problem you find! I'm sure there're still some rough edges xD

**Comment by asermax** [comment]
Finally merged the fingerprint branch with master. I think is pretty stable now.
If you have some time, please test this feature! I would like some feedback from someone else other than myself xD

Edit: gonna close the issue for now :3
